apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: reports.metering.openshift.io
  annotations:
    catalog.app.coreos.com/displayName: "Metering Report"
    catalog.app.coreos.com/description: "A metering report for a specific time interval"
spec:
  group: metering.openshift.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: reports
    kind: Report
  additionalPrinterColumns:
  - name: Query
    type: string
    JSONPath: .spec.generationQuery
  - name: Table Name
    type: string
    JSONPath: .status.tableName
  - name: Phase
    type: string
    JSONPath: .status.phase
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
